### ISSUE TITLE
Add optional compression layer

### ISSUE THREAD

**Issue by shakyShane** [BrowserSync/bslive#19]
The following should work, to serve all requests with compression

```yaml
  servers:
    - name: 'a server with compression'
      routes:
        - path: /
          dir: .
          compression: br
```
