### ISSUE TITLE
add support for optional layers on dirs->proxy fallback

### ISSUE THREAD

**Issue by shakyShane** [BrowserSync/bslive#23]
In this example, if a request for `/` is not found on disk in `examples/kitchen-sink`, then the request is forwarded to the proxy.

At that point, the options for the route are lost, this doesn't work as you'd expect it to

```yaml
servers:
  - bind_address: 0.0.0.0:3000
    routes:
      - path: /
        dir: examples/kitchen-sink
      - path: /
        proxy: https://browsersync.io
        delay:
          ms: 2000 # This won't take effect
```
