### ISSUE TITLE
Should support home dir `~/`

### ISSUE THREAD

**Issue by shakyShane** [BrowserSync/bslive#48]
Make this work:

```yaml
servers:
- name: ‘my server'
  routes: 
  - path: /files 
    dir: ~/Downloads 
    delay: { ms: 2000 }
```
